language: node_js
dist: trusty
sudo: required
node_js:
  - '8.9.4'

before_script:
  npm install -g typescript
  npm install

script:
  npm run build

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  local_dir: dist
  verbose: true